import { Montserrat } from "next/font/google";
import "./globals.css";

const font = Montserrat({
  variable: "--font",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Mockup App",
  icons:{
    icon: "/icons/favicon.ico"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${font.variable}`}>
        {children}
      </body>
    </html>
  );
}
